; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
default_envs = mkrwifi1010

[env]
platform = atmelsam@4.5.1
platform_packages = framework-arduino-samd@1.8.6
framework = arduino
lib_deps =
    adafruit/Adafruit BusIO
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1327
    paulstoffregen/Encoder
    greiman/SdFat
    mikalhart/TinyGPSPlus
    paulstoffregen/Time
    arduino-libraries/RTCZero
    adafruit/Adafruit PM25 AQI Sensor
    https://github.com/Seeed-Studio/Grove_BMP280.git
    https://github.com/jcomas/S8_UART.git

[env:mkrwifi1010]
board = mkrwifi1010

[env:mkrzero]
board = mkrzero

[env:mkr1000]
board = mkr1000USB